FROM ubuntu:18.04

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

ENV R_VERSION=4.0.3
ENV TERM=xterm
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV R_HOME=/usr/local/lib/R
#ENV CRAN=https://mirrors.aliyun.com/CRAN/
ENV CRAN=http://172.17.0.1:9000/packagemanager.rstudio.com/cran/__linux__/bionic/latest/
ENV TZ=Etc/UTC

COPY scripts /rocker_scripts
#COPY scripts/install_R.sh /rocker_scripts/install_R.sh

RUN /rocker_scripts/install_R.sh


CMD ["R"]



